# ci github action
name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.13

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test

      - name: Check code formatting
        run: bun format:check
