name: Publish (React)

on:
  push:
    tags:
      - react-v*

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.30

      # npm 공용 레지스트리에 배포
      - name: Publish to npm
        run: |
          bun install
          bun run build
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
          bun run --filter=@woohm402/eslint-config-react deploy
